/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define PERIPH_BASE		0x40000000UL
#define APB1PERIPH_BASE PERIPH_BASE
#define APB2PERIPH_BASE (PERIPH_BASE + 0x00010000UL)
#define AHB1PERIPH_BASE (PERIPH_BASE + 0x00020000UL)
#define AHB2PERIPH_BASE (PERIPH_BASE + 0x10000000UL)

#define GPIOA_BASE 		(AHB1PERIPH_BASE + 0x0000UL)
#define GPIOC_BASE		(AHB1PERIPH_BASE + 0x0800UL)
#define RCC_BASE		(AHB1PERIPH_BASE + 0x3800UL)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
typedef struct
{
	volatile uint32_t CR;
	uint32_t RV1[11];
	volatile uint32_t AHB1;
	volatile uint32_t AHB2;
	uint32_t RV2[2];
	volatile uint32_t APB1;
	volatile uint32_t APB2;
}RCC_OFF;

#define RCC 			((RCC_OFF *) RCC_BASE)
typedef struct
{
	volatile uint32_t MODE;
	volatile uint32_t TYPE;
	volatile uint32_t SPEED;
	volatile uint32_t IN;
	volatile uint32_t OUT;
	volatile uint32_t BSRR;
	volatile uint32_t PU;
}GPIO_OFF;

#define PA				((GPIO_OFF *) GPIOA_BASE)
#define PC				((GPIO_OFF *) GPIOC_BASE)

void clock_Init(void)
{
	RCC->CR |= (1<<0);
	RCC->AHB1 |= (1<<0) | (1<<2);
}
void myDelay(uint32_t time)
{
	uint32_t i;
	while(time--)
	{
		for(i=0;i<1000;i++);
	}
}
void GPIO_Init(void)
{
	clock_Init();
	PC->PU |= (1<<26); //GPIOC.13 input pullup
	PA->MODE |= (1<<10); //GPIOA.5 moder5 output
	PA->TYPE &= ~(1<<5); //GPIOA.5 type push-pull mode
	PA->SPEED |= (1<<10); //GPIOA.5 speed medium speed
}
int main(void)
{
    clock_Init();
    GPIO_Init();
    PA->OUT |= (1<<5);
    for(;;)
    {
    	if((PC->IN & (1<<13))==0)
    		{
    			myDelay(20);
    			if((PC->IN & (1<<13))==0)
    			{
    				PA->OUT ^= (1<<5);
    			}
    		}
    }


}
